---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: conta-develop
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: io.github.diegolirio
    name: conta-develop
  spec:
    ports:
    - nodePort: 30081
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: conta-develop
      provider: fabric8
      group: io.github.diegolirio
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: conta-develop
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: io.github.diegolirio
    name: conta-develop
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: conta-develop
        provider: fabric8
        group: io.github.diegolirio
    template:
      metadata:
        labels:
          app: conta-develop
          provider: fabric8
          version: 0.0.1-SNAPSHOT
          group: io.github.diegolirio
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/actuator/prometheus'
          prometheus.io/port: '8080'          
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SPRING_PROFILES_ACTIVE
            value: develop
          image: diegolirio/conta:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: spring-boot-starter-parent
          securityContext:
            privileged: false